app:
  name: gin-app
  port: 8080

log:
  name: gin-app
  level: debug
  model: file
  dir: logs

mysql_demo:
  log_file: "logs/sql.log"
  log_slow_threshold: 1000
  colorful: true
  data_source:
    db_driver: "mysql"
    db_name: "demo"
    user_name: "root"
    password: "123456"
    address: "127.0.0.1:3306"
    conn_timeout: 1000 #ms
    read_timeout: 1000
    write_timeout: 1000
    max_open_conn: 10
    max_idle_conn: 10
    conn_max_life_time: 1000 # 单位 ms
    params:
      - key: "charset"
        value: "utf8mb4"

postgres_demo:
  log_file: "logs/sql.log"
  log_slow_threshold: 1000
  colorful: true
  data_source:
    db_driver: "pgx"
    db_name: "demo"
    name: "root"
    password: "123456"
    address: "127.0.0.1"
    max_open_conn: 10
    max_idle_conn: 10
    conn_max_life_time: 1000 # 单位 ms


redis_demo:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

kafka_demo:
  brokers:
    - "39.106.80.226:9092"
  topic: "app_topic_dev"
  group_id: "app_consumer_group_dev"
  auto_offset_reset: "earliest"

mqtt_demo:
  broker: tcp://127.0.0.1:1883
  client_id: mqtt_demo_client
  topic: demo/topic

es_demo:
  addresses:
    - "http://127.0.0.1:9200"
  timeout: 10