// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/user/add": {
            "post": {
                "description": "添加用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用户添加接口",
                "parameters": [
                    {
                        "description": "添加参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-do_User"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/api/user/get": {
            "get": {
                "description": "通过用户ID查询用户详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-do_User"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-any"
                        }
                    },
                    "404": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-any"
                        }
                    }
                }
            }
        },
        "/api/user/query": {
            "post": {
                "description": "分页查询用户列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用户查询接口",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UserQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功响应",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-array_do_User"
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "$ref": "#/definitions/http.BaseResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "do.User": {
            "type": "object",
            "properties": {
                "client_id": {
                    "description": "客户端ID",
                    "type": "string",
                    "example": "xasdfsdf"
                },
                "email": {
                    "description": "用户邮箱",
                    "type": "string",
                    "example": "bill@126.com"
                },
                "id": {
                    "description": "用户ID",
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "description": "用户名称",
                    "type": "string",
                    "example": "bill"
                },
                "password": {
                    "description": "用户密码",
                    "type": "string",
                    "example": "xlasiefska"
                }
            }
        },
        "http.BaseResponse-any": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "实际数据"
                },
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.BaseResponse-array_do_User": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "实际数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/do.User"
                    }
                },
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "http.BaseResponse-do_User": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "description": "实际数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/do.User"
                        }
                    ]
                },
                "message": {
                    "description": "消息",
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "request.UserAddRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "用户邮箱",
                    "type": "string",
                    "example": "bill@126.com"
                },
                "name": {
                    "description": "用户名称",
                    "type": "string",
                    "example": "bill"
                },
                "password": {
                    "description": "用户密码",
                    "type": "string",
                    "example": "111111"
                }
            }
        },
        "request.UserQueryRequest": {
            "type": "object",
            "required": [
                "page",
                "size"
            ],
            "properties": {
                "page": {
                    "description": "页码，从1开始",
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "description": "每页数量",
                    "type": "integer",
                    "example": 10
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Gin App API",
	Description:      "这是gin-app服务的接口文档.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
